import assert from 'node:assert/strict';
import { semanticWikiUI, wikiSemanticView, wikiHistoryHTML, wikiReadingDay, wikiHistoryTime, wikiReadingQuery, restoreWikiReadingRoute, loadWikiReadingPages } from '../src/wiki-semantic-ui.ts';
const ref={kind:'raw_material',id:'raw-a',revision:1,hash:'a'.repeat(64)};
const fact={id:'k1',scope_type:'project',scope_id:'p1',knowledge_type:'fact',status:'current',content:'周一提交红色原型。',source_refs:[ref],tags:[],revision:2,updated_at:'2026-09-28T08:00:00Z'};
const observation={...fact,id:'k2',scope_id:'p2',knowledge_type:'observation',content:'先确认边界，再安排实现。',updated_at:'2026-09-28T09:00:00Z'};
const data={state:{opportunities:[]},workDomain:{projects:[{id:'p1',name:'星舟原型'},{id:'p2',name:'北岸工具'},{id:'p3',name:'空项目'}],employments:[],persons:[]},wikiSemantic:{items:[fact,observation,{...fact,id:'secret',scope_type:'opportunity',content:'不该进入首页'}],raw:[],sourceCatalog:[{source_ref:ref,title:'9月27日原型复盘'}]}};
Object.assign(semanticWikiUI,{browse:'recent',scope:'all',status:'current',selected:'',legacyView:false});
const before=structuredClone(data); const home=wikiSemanticView(data);
for(const name of ['最近更新','项目','任职','人物','长期认知']) assert.ok(home.includes(name));
assert.match(home,/aria-label="Wiki 浏览"/);
assert.doesNotMatch(home,/不该进入首页|全部知识|无 Tags|Fact|scope|revision(?![\w-])/);
assert.ok(home.indexOf(observation.content)<home.indexOf(fact.content),'最近更新按更新时间，不按类型');
const firstRow=home.slice(home.indexOf('<button class="reading-row"'),home.indexOf('</button>',home.indexOf('<button class="reading-row"')));
assert.ok(firstRow.indexOf('reading-excerpt')<firstRow.indexOf('<strong>'),'知识正文先于对象名称');
assert.ok(firstRow.indexOf('<strong>')<firstRow.indexOf('reading-row-meta'),'对象名称先于低权重 metadata');
assert.match(home,/来源 · 原型复盘/,'来源标题去掉重复日期');
assert.doesNotMatch(home,/<small>周一|已确认事实|data-d1-add-raw|data-d1-add-wiki/,'首页是正文列表而非类型/写入后台');
Object.assign(semanticWikiUI,{browse:'project'}); const groups=wikiSemanticView(data);
assert.match(groups,/星舟原型/); assert.match(groups,/北岸工具/); assert.doesNotMatch(groups,/空项目/);
Object.assign(semanticWikiUI,{scope:'project:p1',selected:'k1'}); const detail=wikiSemanticView(data);
assert.match(detail,/已确认事实/); assert.match(detail,/9月27日原型复盘/); assert.match(detail,/更多操作/); assert.match(detail,/data-d1-wiki-history="k1"/); assert.match(detail,/data-d1-open-raw-hash="a{64}"/);
assert.doesNotMatch(detail,/无 Tags|手工原文|北岸工具|不该进入首页/);
assert.deepEqual(data,before,'阅读不改变原对象');
const revisions=[{...fact,revision:1,content:'周五提交蓝色原型。'},{...fact,revision:2},{...fact,revision:3,status:'retired'}];
const history=wikiHistoryHTML(revisions,[{source_ref:ref,title:'2026年9月28日 · 交付计划调整'}]);
assert.match(history,/不再有效/); assert.match(history,/之前的变化/); assert.match(history,/首次记录/); assert.match(history,/26年9月28日 16:00/); assert.match(history,/交付计划调整 →/); assert.doesNotMatch(history,/上一版本|更早版本|正文已修改|已确认事实|查看来源|<details/); assert.doesNotMatch(history,/>当前</);
assert.equal((wikiHistoryHTML(revisions.slice(0,2),[]).match(/>当前</g)||[]).length,1);
assert.equal(wikiReadingDay('2026-09-28T08:00:00Z',new Date('2026-09-28T08:01:00Z')),'今天');
assert.equal(wikiReadingDay('2026-09-27T03:00:00Z',new Date('2026-09-28T08:01:00Z')),'昨天');
assert.equal(wikiReadingDay('2026-09-26T03:00:00Z',new Date('2026-09-28T08:01:00Z')),'9月26日');
assert.equal(wikiHistoryTime('2026-09-28T08:10:00Z'),'26年9月28日 16:10');
const cognitionHome=wikiSemanticView({...data,wikiSemantic:{...data.wikiSemantic,items:[{...fact,id:'cognition-k',scope_type:'cognition',scope_id:'cognition',content:'多个项目都先梳理边界。'}]}});
assert.doesNotMatch(cognitionHome,/<strong>长期认知<\/strong>/,'长期认知不重复显示为对象名');
Object.assign(semanticWikiUI,{browse:'recent',scope:'all',status:'current',selected:'k1',historyId:'k1'});
const historyPage=wikiSemanticView({...data,wikiSemantic:{...data.wikiSemantic,history_revisions:revisions,history_catalog:[]}});
assert.match(historyPage,/reading-history-current/); assert.doesNotMatch(historyPage,/aria-label="Wiki 浏览"|<dialog/,'历史使用可恢复的 Wiki 页面视图');
assert.ok(historyPage.indexOf('周一提交红色原型。')<historyPage.indexOf('周五提交蓝色原型。'),'当前版本先于旧版本');
const historyRoute=wikiReadingQuery(); assert.match(historyRoute,/history=k1/);
restoreWikiReadingRoute(new URLSearchParams(historyRoute)); assert.equal(semanticWikiUI.historyId,'k1');
Object.assign(semanticWikiUI,{browse:'recent',scope:'project:p1',status:'current',selected:'k1',historyId:''});
const query=wikiReadingQuery(); Object.assign(semanticWikiUI,{browse:'recent',scope:'all',selected:''}); restoreWikiReadingRoute(new URLSearchParams(query)); assert.equal(semanticWikiUI.scope,'project:p1');assert.equal(semanticWikiUI.selected,'k1');
// Every page is reachable; metadata-only source titles stay paired with their page.
const calls=[];const pages=[{items:[fact],source_catalog:[{source_ref:ref,title:'复盘'}],next_cursor:'next'},{items:[observation],source_catalog:[],next_cursor:''}];
const loaded=await loadWikiReadingPages(async path=>{calls.push(path);return pages.shift();},new URLSearchParams({status:'current',limit:'50'}));
assert.equal(loaded.items.length,2);assert.equal(loaded.source_catalog.length,1);assert.match(calls[1],/cursor=next/);assert.equal(calls.length,2);
const historyCalls=[];const historyLoaded=await loadWikiReadingPages(async path=>{
 historyCalls.push(path);
 if(path.startsWith('/wiki?')) return {items:[],source_catalog:[],next_cursor:''};
 if(path==='/wiki/k1/history') return {revisions};
 if(path==='/raw?scope_type=project&scope_id=p1') return {items:[{id:'raw-a',title:'项目复盘'}]};
 throw new Error('unexpected Wiki history request: '+path);
},new URLSearchParams({status:'current',limit:'50',history:'k1'}));
assert.equal(historyLoaded.history_revisions.length,3); assert.equal(historyLoaded.history_catalog[0].title,'项目复盘');
assert.doesNotMatch(historyCalls[0],/history=/,'history id 不会泄漏到知识列表接口');
console.log('wiki-reading: ok');
