type Row = Record<string, any>;
const esc = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Api = (path: string, body?: Row, method?: string) => Promise<any>;
type Deps = {state: Row; api: Api; modal: (title:string, body:string, ready?: (d:HTMLDialogElement)=>void)=>HTMLDialogElement; modalError:(e:unknown)=>void; load:()=>Promise<void>; render:()=>void; inform:(text:string)=>void};

export function aiSettingsView(state: Row, modeText: string) {
  const ai = state.ai || {configs: [], default_model_config_id: null};
  const rows = (ai.configs || []).map((config: Row) => `<article class="ai-config-row"><div><h3>${esc(config.display_name)}</h3><p>${esc(config.provider)} · ${esc(config.model)}</p><small>${esc(config.base_url)} · ${config.api_key_set ? '••••••••' : '未设置 Key'}${config.id === ai.default_model_config_id ? ' · 当前使用' : ''}</small></div><div class="actions"><button class="secondary" data-ai-test="${esc(config.id)}">测试</button>${config.id === ai.default_model_config_id ? '<span class="pill">当前使用</span>' : `<button class="quiet" data-ai-default="${esc(config.id)}">设为当前</button>`}<button class="quiet" data-ai-edit="${esc(config.id)}">编辑</button><button class="text-btn" data-ai-delete="${esc(config.id)}">删除</button></div></article>`).join('');
  const current = (ai.configs || []).find((config: Row) => config.id === ai.default_model_config_id);
  return `<section class="settings scroll"><div class="pane-heading"><h2>AI 模型</h2><div class="actions"><button class="primary" id="ai-add">添加模型</button></div></div><p class="muted">API Key 只保存在 macOS Keychain；Career 数据库、备份、日志和浏览器响应都不保存完整密钥。</p><section class="ai-config-list">${rows || '<div class="empty">尚未配置 AI 模型。人工资料、简历和求职记录仍可正常使用。</div>'}</section><div class="setting-row"><span>当前模式</span><b>${esc(modeText)}</b></div><div class="setting-row"><span>默认模型</span><span>${current ? esc(`${current.provider} / ${current.model}`) : '尚未设置，AI 操作会提示进入本页配置模型'}</span></div><button class="text-btn" data-page="feedback">查看反馈记录 →</button></section>`;
}

export function bindAiSettings(d: Deps) {
  const form = (current?: Row) => {
    const editing = Boolean(current);
    const dialog = d.modal(editing ? '编辑模型配置' : '添加模型', `<form id="ai-form"><label>显示名称<input name="display_name" required maxlength="200" value="${esc(current?.display_name)}"></label><label>供应商<input name="provider" required maxlength="100" value="${esc(current?.provider || 'OpenAI-compatible')}"></label><label>Base URL<input name="base_url" required maxlength="2000" type="url" value="${esc(current?.base_url || 'https://api.openai.com/v1')}"></label><label>模型名称<input name="model" required maxlength="500" value="${esc(current?.model)}"></label><p class="muted">DeepSeek 当前模型名称为 <code>deepseek-flash</code>；旧别名会在保存和测试时自动规范化。</p><label>API Key${editing ? '（留空保留旧 Key）' : ''}<input name="api_key" type="password" autocomplete="new-password" maxlength="10000"></label><label><input name="enabled" type="checkbox" ${current?.enabled !== false ? 'checked' : ''}> 启用</label><div class="actions"><button type="button" class="secondary" data-ai-dialog-test>测试连接</button><button type="submit" class="primary">保存</button></div><p class="muted" data-ai-dialog-status></p></form>`);
    const f = dialog.querySelector<HTMLFormElement>('#ai-form')!;
    const values = (): Row => { const raw = Object.fromEntries(new FormData(f).entries()) as Row; return {...raw, enabled: (f.elements.namedItem('enabled') as HTMLInputElement).checked}; };
    const test = async () => { const button = f.querySelector<HTMLButtonElement>('[data-ai-dialog-test]')!; button.disabled = true; try { const raw = values(); const result = await d.api('/ai/test-connection', {provider: raw.provider, base_url: raw.base_url, model: raw.model, api_key: raw.api_key}, 'POST'); (f.querySelector('[data-ai-dialog-status]') as HTMLElement).textContent = result.status === 'success' ? `连接成功（${result.model}）` : `连接失败：${result.code}${result.message ? `（${result.message}）` : ''}`; } catch (e) { (f.querySelector('[data-ai-dialog-status]') as HTMLElement).textContent = e instanceof Error ? e.message : '连接失败'; } finally { button.disabled = false; } };
    dialog.querySelector('[data-ai-dialog-test]')!.addEventListener('click', () => { void test(); });
    f.onsubmit = async event => { event.preventDefault(); const button = f.querySelector<HTMLButtonElement>('[type=submit]')!; button.disabled = true; try { const body: Row = values(); if (editing && current) { body.expected_revision = current.revision; await d.api('/ai/models/' + encodeURIComponent(current.id), body, 'PUT'); } else await d.api('/ai/models', body); dialog.close(); await d.load(); d.render(); d.inform('模型配置已保存。'); } catch (e) { d.modalError(e); } finally { button.disabled = false; } };
  };
  document.querySelector('#ai-add')?.addEventListener('click', () => form());
  document.querySelectorAll<HTMLElement>('[data-ai-edit]').forEach(el => el.onclick = () => form((d.state.ai?.configs || []).find((x:Row) => x.id === el.dataset.aiEdit)));
  document.querySelectorAll<HTMLElement>('[data-ai-test]').forEach(el => el.onclick = async () => { el.setAttribute('aria-busy','true'); try { const result = await d.api('/ai/models/' + encodeURIComponent(el.dataset.aiTest!) + '/test', {}, 'POST'); d.inform(result.status === 'success' ? '连接成功。' : `连接失败：${result.code}`); } catch (e) { d.inform(e instanceof Error ? e.message : '连接失败'); } finally { el.removeAttribute('aria-busy'); } });
  document.querySelectorAll<HTMLElement>('[data-ai-default]').forEach(el => el.onclick = async () => { const config = (d.state.ai?.configs || []).find((x:Row) => x.id === el.dataset.aiDefault); if (!config) return; try { await d.api('/ai/models/' + encodeURIComponent(config.id) + '/default', {expected_revision: config.revision}); await d.load(); d.render(); d.inform('默认模型已切换。'); } catch (e) { d.modalError(e); } });
  document.querySelectorAll<HTMLElement>('[data-ai-delete]').forEach(el => el.onclick = async () => { const id = el.dataset.aiDelete!; const current = id === d.state.ai?.default_model_config_id; if (!window.confirm(current ? '删除当前默认模型后将没有默认 AI 模型。确认删除？' : '删除此模型配置及其 Key？确认删除？')) return; try { await d.api('/ai/models/' + encodeURIComponent(id), {confirm: true}, 'DELETE'); await d.load(); d.render(); d.inform(current ? '已删除模型；当前没有默认 AI 模型。' : '模型配置已删除。'); } catch (e) { d.modalError(e); } });
}
