import { closeDialogIfAllowed, markUntrackedDialogClean, markUntrackedDialogDirty, sessionFor, trackDialogForms } from './edit-session';
type Row = Record<string, any>;
type Actions = {api:<T = Row>(path:string,body?:Row,method?:string)=>Promise<T>;refresh:()=>Promise<void>;go:(id:string,filter?:string)=>void};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const localDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const status:Row={pending:'待排期',scheduled:'已排期',completed:'已完成',cancelled:'已取消'};
const statusLabel=(session:Row)=>session.type==='simulation'&&session.status==='pending'?'待进行':status[session.status]||session.status;
const split=(value:FormDataEntryValue|null)=>String(value||'').split('\n').map(x=>x.trim()).filter(Boolean);
const setFormValue=(form:HTMLFormElement,name:string,value:unknown)=>{const field=form.elements.namedItem(name) as HTMLInputElement|HTMLTextAreaElement|null;if(field)field.value=Array.isArray(value)?value.join('\n'):String(value??'');};

export function interviewStageHTML(o:Row, interviews:Row[]) {
  if(o.read_only||o.result!=='active')return '';
  const real=interviews.filter(x=>x.type==='real');
  const legacy=interviews.filter(x=>x.legacy);
  if(o.phase==='submitted')return `<div class="op-interview-entry"><button class="primary" data-confirm-interview>确认真实面试</button><p class="muted">确认后才进入面试阶段；日期可稍后排期。</p></div>`;
  if(o.phase!=='interview')return '';
  const ordered=[...real].sort((a,b)=>String(b.scheduled_on||b.confirmed_on||'').localeCompare(String(a.scheduled_on||a.confirmed_on||'')));
  const current=ordered.find(x=>['pending','scheduled'].includes(x.status))||ordered[0];
  const previous=ordered.filter(x=>x.id!==current?.id);
  const simulations=current?interviews.filter(x=>x.type==='simulation'&&x.target_real_interview_id===current.id):[];
  const currentCard=current?`<article class="op-current-interview"><div class="op-interview-summary"><div><p class="op-eyebrow">当前 / 下一轮</p><h4>${esc(current.name)}</h4><p>${current.scheduled_on?`预约 ${esc(current.scheduled_on)}`:'时间待定'} · ${esc(statusLabel(current))}</p></div><span>${simulations.length} 次模拟</span></div><div class="actions"><button class="primary" data-interview="${esc(current.id)}" data-interview-intent="preparation">准备这一轮</button><button class="secondary" data-interview="${esc(current.id)}" data-interview-intent="simulation">开始模拟</button><button class="text-btn" data-interview="${esc(current.id)}">打开本轮</button></div>${simulations.length?'':'<p class="muted">还没有进行模拟面试</p>'}</article>`:'<p class="muted">还没有已确认的真实面试。</p>';
  const history=previous.length?`<details class="op-rounds"><summary>查看之前的 ${previous.length} 轮面试</summary>${previous.map(x=>`<button class="op-recent" data-interview="${esc(x.id)}"><span>${esc(x.confirmed_on)} · ${esc(statusLabel(x))}</span><strong>${esc(x.name)}</strong><small>${x.scheduled_on?`预约 ${esc(x.scheduled_on)}`:'时间待定'} · ${interviews.filter(s=>s.type==='simulation'&&s.target_real_interview_id===x.id).length} 次模拟</small></button>`).join('')}</details>`:'';
  return `<div class="op-interview-entry">${currentCard}<div class="actions"><button class="secondary" data-confirm-interview>确认下一轮真实面试</button></div>${history}${legacy.length?`<details><summary>${legacy.length} 条历史面试待核对</summary><p class="muted">类型、日期和状态保持待核对；不会按名称猜测。</p>${legacy.map(x=>`<button class="op-recent" data-interview="${esc(x.id)}"><strong>${esc(x.legacy_name||'历史面试')}</strong><small>只读 · 待显式核对</small></button>`).join('')}</details>`:''}</div>`;
}

export function bindInterviews(o:Row, interviews:Row[], actions:Actions) {
  document.querySelectorAll<HTMLElement>('[data-confirm-interview]').forEach(el=>el.onclick=()=>confirm());
  document.querySelectorAll<HTMLElement>('[data-interview]').forEach(el=>el.onclick=()=>void detail(el.dataset.interview!,el.dataset.interviewIntent));
  function dialog(title:string,body:string){
    const d=document.createElement('dialog');d.className='op-dialog interview-dialog';
    d.innerHTML=`<div class="op-heading"><h2>${esc(title)}</h2><button type="button" data-close>关闭</button></div><div class="op-error" role="alert" hidden></div><div class="op-save-status" role="status" hidden></div>${body}`;
    document.body.append(d);
    trackDialogForms(d);
    d.querySelector('[data-close]')!.addEventListener('click',()=>closeDialogIfAllowed(d));
    d.addEventListener('click',(event)=>{if(event.target===d)closeDialogIfAllowed(d);});
    d.addEventListener('cancel',(event)=>{event.preventDefault();closeDialogIfAllowed(d);});
    d.addEventListener('input',(event)=>{const target=event.target as HTMLElement|null;if(!target?.closest('form'))markUntrackedDialogDirty(d);});
    d.addEventListener('close',()=>d.remove());d.showModal();return d;
  }
  function fail(d:HTMLDialogElement,e:unknown){const a=d.querySelector<HTMLElement>('.op-error')!;a.hidden=false;a.textContent=String((e as Error).message||e);}
  function saved(d:HTMLDialogElement){const a=d.querySelector<HTMLElement>('.op-save-status')!;a.hidden=false;a.textContent='已保存';}
  async function refresh(){await actions.refresh();actions.go(o.id);}
  function confirm(sourceCommunicationId?:string){const d=dialog('确认真实面试',`<form><p>这是现实中已确认的面试。确认日期由系统记录；排期可留空。</p><label>轮次名称<input name="name" required maxlength="500" placeholder="例如：业务一面"></label><label>预约日期（可选）<input name="scheduled_on" type="date"></label><input name="source_communication_id" type="hidden" value="${esc(sourceCommunicationId||'')}"><button class="primary" type="submit">确认面试</button></form>`);const f=d.querySelector('form')!;let pending:Row|undefined;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const base:Row={name:String(fd.get('name')),scheduled_on:String(fd.get('scheduled_on')||'')||null,scheduled_at:null,expected_opportunity_revision:o.revision};const source=String(fd.get('source_communication_id')||'');if(source)base.source_communication_id=source;if(!pending)pending={...base,idempotency_key:crypto.randomUUID()};try{await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/real`,pending);d.close();await refresh();}catch(error){fail(d,error);}};}
  async function optional(path:string){try{return await actions.api(path);}catch(e){if((e as any).status===404)return null;throw e;}}
  async function generateAi(d:HTMLDialogElement,s:Row,kind:'review'|'patch'){
    const path=`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/${kind==='review'?'generate-final-review':'generate-research-patch'}`;
    const request:Row={communication_ids:[],wiki_ids:[],idempotency_key:crypto.randomUUID()};
    try{
      let result:Row;
      try{result=await actions.api(path,request);}catch(error){
        const apiError=error as any;
        if(apiError.status!==409||!apiError.data?.prepared_id)throw error;
        if(!window.confirm('将按当前面试资料生成 AI 建议。确认后才会发送到当前配置的 Provider；没有真实 Provider 时会明确返回失败。'))return;
        result=await actions.api(path,{...request,prepared_id:apiError.data.prepared_id,payload_hash:apiError.data.payload_hash,confirm_outbound:true});
      }
      d.close();
      await refresh();
      if(result?.mode==='test') window.dispatchEvent(new CustomEvent('career-ai-test-result'));
    }catch(error){fail(d,error);}
  }
  async function detail(id:string,intent?:string){try{const session=await actions.api<Row>(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(id)}`);if(session.legacy){legacyUpgrade(session);return;}const [prep,raw,review,patches]=await Promise.all([session.type==='real'?actions.api<Row>(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(id)}/preparation`):Promise.resolve(null),session.type==='real'?optional(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(id)}/raw`):Promise.resolve(null),optional(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(id)}/final-review`),session.type==='real'?actions.api<Row[]>(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(id)}/research-patches`):Promise.resolve([] as Row[])]);openDetail(session,prep,raw,review,patches,intent);}catch(error){const d=dialog('面试不可用','<p>无法读取该轮次。</p>');fail(d,error);}}
  function legacyUpgrade(s:Row){const realOptions=interviews.filter(x=>x.type==='real').map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');const d=dialog('历史 Interview',`<p class="notice">类型、状态和日期均待核对；系统不会按名称猜测。</p><pre>${esc(JSON.stringify(s,null,2))}</pre><form data-upgrade><label>核对类型<select name="type"><option value="real">真实面试</option><option value="simulation">模拟面试</option></select></label><label>轮次名称<input name="name" required value="${esc(s.legacy_name||'')}"></label><label>状态<select name="status"><option value="pending">待排期</option><option value="scheduled">已排期</option><option value="completed">已完成</option><option value="cancelled">已取消</option></select></label><label>确认日期<input name="confirmed_on" type="date" required></label><label>预约日期（scheduled 时必填）<input name="scheduled_on" type="date"></label><label>完成日期（completed 时必填）<input name="completed_on" type="date"></label><label>取消日期（cancelled 时必填）<input name="cancelled_on" type="date"></label><label>模拟所绑定真实轮次<select name="target_real_interview_id"><option value="">真实面试无需选择</option>${realOptions}</select></label><button class="primary" type="submit">按以上明确事实升级同一 ID</button></form>`);const f=d.querySelector<HTMLFormElement>('[data-upgrade]')!;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const value=(k:string)=>String(fd.get(k)||'')||null;try{await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/upgrade`,{type:value('type'),name:value('name'),status:value('status'),confirmed_on:value('confirmed_on'),scheduled_on:value('scheduled_on'),scheduled_at:null,completed_on:value('completed_on'),cancelled_on:value('cancelled_on'),target_real_interview_id:value('target_real_interview_id'),expected_revision:s.revision,expected_opportunity_revision:o.revision,idempotency_key:crypto.randomUUID()});d.close();await refresh();}catch(error){fail(d,error);}};}
  function openDetail(s:Row,prep:Row|null,raw:Row|null,review:Row|null,patches:Row[],intent?:string){const simulations=interviews.filter(x=>x.type==='simulation'&&x.target_real_interview_id===s.id);const reviewOptions=interviews.filter(x=>x.id!==s.id&&x.has_final_review).map(x=>`<label class="check"><input type="checkbox" name="review_id" value="${esc(x.final_review_id)}">${esc(x.name)} 的面试复盘</label>`).join('');const patchList=patches.filter(x=>x.origin_interview_id===s.id).map(x=>`<article class="op-record"><strong>岗位情报更新建议 · ${x.status==='pending'?'待确认':x.status==='accepted'?'已采用':'已忽略'}</strong><details><summary>查看结构化建议</summary><textarea data-patch-items="${esc(x.id)}" rows="5" ${x.status==='pending'?'':'readonly'}>${esc(JSON.stringify(x.items,null,2))}</textarea></details>${x.status==='pending'?`<div class="actions"><button data-patch-save="${esc(x.id)}" data-revision="${x.revision}">保存编辑</button><button data-patch-accept="${esc(x.id)}" data-revision="${x.revision}">采用并更新岗位情报</button><button data-patch-reject="${esc(x.id)}" data-revision="${x.revision}">忽略</button></div>`:''}</article>`).join('');const simulationSection=s.type==='real'?`<section data-pane="simulation"><h3>模拟面试</h3><form data-simulation><p class="muted">选择过去面试的复盘作为参考，可多选，也可以不选。</p>${reviewOptions||'<p class="muted">暂无可选择的历史面试复盘；可以直接开始。</p>'}<button type="submit">创建模拟并准备资料包</button></form>${simulations.length?simulations.map(x=>`<button class="op-recent" data-open-sim="${esc(x.id)}"><strong>${esc(x.name)}</strong><small>${esc(statusLabel(x))}</small></button>`).join(''):'<p class="muted">还没有进行模拟面试</p>'}<div data-simulation-result></div></section>`:'';const patchSection=s.type==='real'?`<section><h3>岗位情报更新建议</h3><p class="muted">只对真实面试开放；模拟面试不会生成现实研究 Patch。</p><button class="secondary" data-generate-patch>提议研究补丁</button>${patchList||'<p class="muted">暂无待确认的岗位情报建议。</p>'}</section>`:'';const d=dialog(s.name,`<p class="op-eyebrow">${s.type==='real'?'真实面试':'模拟面试'} · ${esc(statusLabel(s))}</p>${s.source_communication?`<details><summary>来源沟通${s.source_communication.archived?'（已归档）':''}</summary><p>${esc(s.source_communication.content||'来源缺失')}</p></details>`:''}<section><h3>本轮状态</h3><div class="actions">${s.type==='real'?'<button data-schedule>排期 / 改期</button><button data-pending>待重约</button>':''}<button data-complete>完成</button><button data-cancel>取消</button></div></section>${s.type==='real'?prepHTML(prep!):''}${simulationSection}${s.type==='real'?rawHTML(raw):''}${reviewHTML(review,s)}${patchSection}`);
    d.querySelector<HTMLElement>('[data-generate-review]')?.addEventListener('click',()=>void generateAi(d,s,'review'));d.querySelector<HTMLElement>('[data-generate-patch]')?.addEventListener('click',()=>void generateAi(d,s,'patch'));
    bindStatus(d,s);if(s.type==='real')bindPrep(d,s,prep!);if(s.type==='real')bindRaw(d,s,raw);bindReview(d,s,review);d.querySelectorAll<HTMLElement>('[data-open-sim]').forEach(x=>x.onclick=()=>{if(closeDialogIfAllowed(d))void detail(x.dataset.openSim!);});const simForm=d.querySelector<HTMLFormElement>('[data-simulation]');if(simForm)simForm.onsubmit=async e=>{e.preventDefault();const ids=[...new FormData(simForm).getAll('review_id')].map(String);try{const result=await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/simulations`,{selected_review_ids:ids,communication_ids:[],wiki_ids:[],idempotency_key:crypto.randomUUID()});const box=d.querySelector<HTMLElement>('[data-simulation-result]')!;const pack=JSON.stringify(result.context_pack,null,2);box.innerHTML=`<p class="notice">模拟已创建，资料包包含 ${Number(result.context_pack?.sources?.length||0)} 条明确来源。</p><div class="actions"><button data-copy-pack>复制模拟资料包</button><button data-open-created-sim>打开这次模拟</button></div>`;box.querySelector<HTMLElement>('[data-copy-pack]')!.onclick=()=>void navigator.clipboard.writeText(pack);box.querySelector<HTMLElement>('[data-open-created-sim]')!.onclick=()=>{if(closeDialogIfAllowed(d))void detail(result.interview.id);};await actions.refresh();}catch(error){fail(d,error);}};
    d.querySelectorAll<HTMLElement>('[data-patch-save]').forEach(x=>x.onclick=()=>void savePatch(d,x.dataset.patchSave!,Number(x.dataset.revision)));d.querySelectorAll<HTMLElement>('[data-patch-accept],[data-patch-reject]').forEach(x=>x.onclick=()=>void resolvePatch(d,x.dataset.patchAccept?'accept':'reject',x.dataset.patchAccept||x.dataset.patchReject!,Number(x.dataset.revision)));if(intent)requestAnimationFrame(()=>d.querySelector<HTMLElement>(`[data-pane="${CSS.escape(intent)}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}));
  }
  const prepHTML=(p:Row)=>`<section data-pane="preparation"><h3>面试准备</h3><form data-prep><p class="muted">按当前需要填写即可，可以只准备其中一部分。</p><label>面试重点<textarea name="focus">${esc(p.focus)}</textarea></label><label>预计问题（每行一项）<textarea name="expected_questions">${esc((p.expected_questions||[]).join('\n'))}</textarea></label><label>重点项目（每行一项）<textarea name="priority_projects">${esc((p.priority_projects||[]).join('\n'))}</textarea></label><label>风险问题（每行一项）<textarea name="risks">${esc((p.risks||[]).join('\n'))}</textarea></label><label>我的备注<textarea name="notes">${esc(p.notes)}</textarea></label><button type="submit">保存面试准备</button></form></section>`;
  const rawHTML=(r:Row|null)=>`<section><h3>面试记录</h3><p class="muted">保存这一轮真实面试的原始记录；后续复盘不会覆盖它。</p><form data-raw><textarea name="content" rows="8" required>${esc(r?.content||'')}</textarea><button type="submit">保存面试记录</button></form></section>`;
  const reviewHTML=(r:Row|null,s:Row)=>`<section><h3>面试复盘</h3><div class="actions"><button type="button" class="secondary" data-generate-review>生成复盘建议</button><span class="muted">未确认发送前不会调用 Provider；无真实 Provider 时会显示配置错误。</span></div><form data-review><label>总结<textarea name="summary" required>${esc(r?.summary||'')}</textarea></label>${[['key_qa','关键问答'],['patterns','模式'],['discoveries','新发现'],['next_actions','下一步']].map(([k,l])=>`<label>${l}（每行一项）<textarea name="${k}">${esc((r?.[k]||[]).join('\n'))}</textarea></label>`).join('')}<button type="submit">保存面试复盘</button></form></section>`;
  function scheduleDialog(parent:HTMLDialogElement,s:Row){const d=dialog('排期 / 改期',`<form data-schedule-form><p>日期可以单独保存；未填写日期时取消本次操作，不会发送请求。</p><label>预约日期<input name="scheduled_on" type="date" required value="${esc(s.scheduled_on||'')}"></label><button class="primary" type="submit">保存排期</button></form>`);const f=d.querySelector<HTMLFormElement>('[data-schedule-form]')!;const session=sessionFor(f);f.onsubmit=async e=>{e.preventDefault();const scheduled_on=String(new FormData(f).get('scheduled_on')||'');if(!scheduled_on)return;await statusAction(parent,s,'schedule',{scheduled_on,scheduled_at:null},d,()=>session.markSaved());};}
  function bindStatus(d:HTMLDialogElement,s:Row){d.querySelector<HTMLElement>('[data-schedule]')?.addEventListener('click',()=>scheduleDialog(d,s));d.querySelector<HTMLElement>('[data-pending]')?.addEventListener('click',()=>void statusAction(d,s,'pending',{}));d.querySelector<HTMLElement>('[data-complete]')!.onclick=()=>void statusAction(d,s,'complete',{completed_on:localDay()});d.querySelector<HTMLElement>('[data-cancel]')!.onclick=()=>void statusAction(d,s,'cancel',{cancelled_on:localDay()});}
  async function statusAction(d:HTMLDialogElement,s:Row,action:string,extra:Row,closeTarget=d,afterSave=()=>{}){if(action==='schedule'&&extra.scheduled_on===null)return;try{const response=await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/${action}`,{...extra,expected_revision:s.revision,idempotency_key:crypto.randomUUID()});Object.assign(s,response);afterSave();if(closeDialogIfAllowed(closeTarget))await refresh();else{saved(d);await refresh();}}catch(error){fail(closeTarget,error);}}
  function bindPrep(d:HTMLDialogElement,s:Row,p:Row){const f=d.querySelector<HTMLFormElement>('[data-prep]')!;const session=sessionFor(f);let preparation=p;let saving=false;f.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;const button=f.querySelector<HTMLButtonElement>('button[type=submit]');if(button)button.disabled=true;const fd=new FormData(f);try{const response=await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/preparation`,{focus:String(fd.get('focus')),expected_questions:split(fd.get('expected_questions')),priority_projects:split(fd.get('priority_projects')),risks:split(fd.get('risks')),notes:String(fd.get('notes')),expected_revision:preparation.revision,idempotency_key:crypto.randomUUID()},'PUT');preparation=response;for(const [name,value] of Object.entries(response))setFormValue(f,name,value);session.markSaved();saved(d);}catch(error){fail(d,error);}finally{saving=false;if(button)button.disabled=false;}};}
  function bindRaw(d:HTMLDialogElement,s:Row,r:Row|null){const f=d.querySelector<HTMLFormElement>('[data-raw]')!;const session=sessionFor(f);let raw=r;let saving=false;f.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;const button=f.querySelector<HTMLButtonElement>('button[type=submit]');if(button)button.disabled=true;try{const response=await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/raw`,{content:String(new FormData(f).get('content')),expected_revision:raw?.revision||0,idempotency_key:crypto.randomUUID()},'PUT');raw=response;setFormValue(f,'content',response.content);session.markSaved();saved(d);}catch(error){fail(d,error);}finally{saving=false;if(button)button.disabled=false;}};}
  function bindReview(d:HTMLDialogElement,s:Row,r:Row|null){const f=d.querySelector<HTMLFormElement>('[data-review]')!;const session=sessionFor(f);let review=r;let saving=false;f.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;const button=f.querySelector<HTMLButtonElement>('button[type=submit]');if(button)button.disabled=true;const fd=new FormData(f);try{const response=await actions.api(`/opportunities/${encodeURIComponent(o.id)}/interviews/${encodeURIComponent(s.id)}/final-review`,{summary:String(fd.get('summary')),key_qa:split(fd.get('key_qa')),patterns:split(fd.get('patterns')),discoveries:split(fd.get('discoveries')),next_actions:split(fd.get('next_actions')),expected_revision:review?.revision||0,idempotency_key:crypto.randomUUID()},'PUT');review=response;for(const [name,value] of Object.entries(response))setFormValue(f,name,value);session.markSaved();saved(d);}catch(error){fail(d,error);}finally{saving=false;if(button)button.disabled=false;}};}
  async function savePatch(d:HTMLDialogElement,id:string,revision:number){try{const field=d.querySelector<HTMLTextAreaElement>(`[data-patch-items="${CSS.escape(id)}"]`)!;const items=JSON.parse(field.value);await actions.api(`/opportunities/${encodeURIComponent(o.id)}/research-patches/${encodeURIComponent(id)}`,{items,expected_revision:revision,idempotency_key:crypto.randomUUID()},'PUT');markUntrackedDialogClean(d);saved(d);if(closeDialogIfAllowed(d))await refresh();}catch(e){fail(d,e);}}
  async function resolvePatch(d:HTMLDialogElement,decision:string,id:string,revision:number){try{await actions.api(`/opportunities/${encodeURIComponent(o.id)}/research-patches/${encodeURIComponent(id)}/resolve`,{decision,expected_revision:revision,idempotency_key:crypto.randomUUID()});markUntrackedDialogClean(d);if(closeDialogIfAllowed(d))await refresh();}catch(e){fail(d,e);}}
  return {confirmFromCommunication:confirm};
}
