/** Offer belongs to one Opportunity; terms are current-only and user-confirmed. */
type Row = Record<string, any>;
type Actions = {api:(path:string,body?:Row,method?:string)=>Promise<any>;refresh:()=>Promise<void>;go:(id:string,filter?:string)=>void};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const localDay=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const emptyComp=()=>({guaranteed_cash:'',variable_cash:'',equity:'',one_time:'',notes:''});
const emptyTerms=()=>({offered_role_title:'',location:'',start_date:null,employment_type:'',probation:'',benefits:'',compensation:emptyComp(),other_terms:''});
const decisionLabel=(value:string)=>({accepted:'已接受',rejected:'招聘方已结束',withdrawn:'已主动退出'} as Record<string,string>)[value]||value;
function summary(label:string,value:unknown){return value?`<div><small>${esc(label)}</small><p>${esc(value)}</p></div>`:'';}

export function offerStageHTML(o:Row,offer:Row|null){
 if(o.read_only)return '';
 if(offer?.legacy)return `<section class="op-offer"><h3>历史 Offer · 待核对</h3><p class="notice">旧日期、条件和状态只读保留，不自动改变阶段或结果。</p>${!offer.note_only&&o.result==='active'&&['submitted','interview'].includes(o.phase)?'<button class="primary" data-upgrade-offer>核对并接管历史 Offer</button>':''}</section>`;
 if(!offer&&o.result==='active'&&['submitted','interview'].includes(o.phase))return `<section class="op-offer"><h3>现实中已收到 Offer？</h3><p>只有明确收到后才记录；面试完成、沟通文字和系统判断都不会自动推进。</p><button class="primary" data-record-offer>记录现实 Offer</button></section>`;
 if(!offer)return '';
 const t=offer.terms||emptyTerms(),c=t.compensation||emptyComp();
 const terms=[summary('Offer 正式岗位',t.offered_role_title),summary('地点',t.location),summary('入职日期',t.start_date),summary('用工类型',t.employment_type),summary('试用期',t.probation),summary('福利',t.benefits),summary('保证现金',c.guaranteed_cash),summary('浮动现金',c.variable_cash),summary('权益',c.equity),summary('一次性项目',c.one_time),summary('薪酬补充',c.notes),summary('其它条件',t.other_terms)].filter(Boolean).join('');
 return `<section class="op-offer" id="op-offer"><div class="op-heading"><div><p class="op-eyebrow">收到日期 · ${esc(offer.received_on)}</p><h3>当前 Offer</h3></div>${o.result==='active'?'<button class="secondary" data-edit-offer>编辑 Offer</button>':''}</div>${terms?`<div class="op-offer-grid">${terms}</div>`:'<p class="muted">尚未单独确认具体 Offer 条件。</p>'}${o.result==='active'?'<div class="actions op-offer-actions"><button class="secondary" data-negotiation>记录谈薪沟通</button><button class="primary" data-accept-offer>接受 Offer</button><button class="secondary" data-end-opportunity="withdrawn">主动退出</button><button class="text-btn" data-end-opportunity="rejected">招聘方结束</button></div>':`<p class="notice">这次机会${esc(decisionLabel(o.result))}。当前条件和历史活动保持可读。</p>`}</section>`;
}

export function bindOffer(o:Row,offer:Row|null,actions:Actions){
 const dialog=(title:string,body:string)=>{const d=document.createElement('dialog');d.className='op-dialog';d.innerHTML=`<div class="op-heading"><h2>${title}</h2><button type="button" data-close>关闭</button></div><div class="op-error" role="alert" hidden></div>${body}`;document.body.append(d);d.querySelector('[data-close]')!.addEventListener('click',()=>d.close());d.addEventListener('input',()=>d.dataset.dirty='true');d.addEventListener('close',()=>d.remove());d.showModal();return d;};
 const fail=(d:HTMLDialogElement,error:unknown)=>{const a=d.querySelector<HTMLElement>('.op-error')!;a.hidden=false;a.textContent=String((error as Error).message);};
 const formHTML=(current?:Row)=>{const t=current?.terms||emptyTerms(),c=t.compensation||emptyComp();return `<form data-offer-form><p><strong>当前机会岗位：</strong>${esc(o.title)}</p><p class="muted">仅作上下文提示，不会自动写入Offer正式岗位名称或其它条件。</p><label>收到日期<input type="date" name="received_on" required value="${esc(current?.received_on||localDay())}"></label><label>Offer正式岗位名称（可选）<input name="offered_role_title" maxlength="500" value="${esc(t.offered_role_title)}"></label><label>地点（可选）<input name="location" value="${esc(t.location)}"></label><label>入职日期（可选）<input type="date" name="start_date" value="${esc(t.start_date||'')}"></label><label>用工类型（可选）<input name="employment_type" value="${esc(t.employment_type)}"></label><label>试用期（可选）<textarea name="probation">${esc(t.probation)}</textarea></label><label>福利（可选）<textarea name="benefits">${esc(t.benefits)}</textarea></label><fieldset><legend>薪酬条件 · 原样记录，不计算总包</legend><label>保证现金<textarea name="guaranteed_cash">${esc(c.guaranteed_cash)}</textarea></label><label>浮动现金<textarea name="variable_cash">${esc(c.variable_cash)}</textarea></label><label>权益<textarea name="equity">${esc(c.equity)}</textarea></label><label>一次性项目<textarea name="one_time">${esc(c.one_time)}</textarea></label><label>薪酬补充<textarea name="compensation_notes">${esc(c.notes)}</textarea></label></fieldset><label>其它条件<textarea name="other_terms" rows="4">${esc(t.other_terms)}</textarea></label><button class="primary" type="submit">${current?'保存当前条件':'确认记录现实 Offer'}</button></form>`;};
 const values=(f:HTMLFormElement)=>{const d=new FormData(f);return {received_on:String(d.get('received_on')),terms:{offered_role_title:String(d.get('offered_role_title')),location:String(d.get('location')),start_date:String(d.get('start_date'))||null,employment_type:String(d.get('employment_type')),probation:String(d.get('probation')),benefits:String(d.get('benefits')),compensation:{guaranteed_cash:String(d.get('guaranteed_cash')),variable_cash:String(d.get('variable_cash')),equity:String(d.get('equity')),one_time:String(d.get('one_time')),notes:String(d.get('compensation_notes'))},other_terms:String(d.get('other_terms'))}};};
 const edit=(mode:'record'|'update'|'upgrade')=>{const current=mode==='update'?offer:null;const d=dialog(mode==='update'?'编辑当前 Offer':mode==='upgrade'?'核对历史 Offer':'记录现实 Offer',formHTML(current||undefined));const f=d.querySelector<HTMLFormElement>('form')!;let pending:Row|undefined,signature='';f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector<HTMLButtonElement>('button[type=submit]')!;b.disabled=true;const data=values(f);const base:Row={...data,...(mode==='update'?{expected_revision:offer!.revision}:mode==='upgrade'?{expected_opportunity_revision:o.revision,expected_legacy_hash:offer!.legacy_hash,confirmed:true}:{expected_opportunity_revision:o.revision})};const next=JSON.stringify(base);if(!pending||next!==signature){signature=next;pending={...base,idempotency_key:crypto.randomUUID()};}try{const path=mode==='record'?`/opportunities/${encodeURIComponent(o.id)}/offer`:`/opportunities/${encodeURIComponent(o.id)}/offer/${encodeURIComponent(offer!.id)}${mode==='upgrade'?'/upgrade':''}`;await actions.api(path,pending,mode==='update'?'PUT':'POST');d.close();await actions.refresh();actions.go(o.id);}catch(error){fail(d,error);}finally{b.disabled=false;}};};
 document.querySelector<HTMLElement>('[data-record-offer]')?.addEventListener('click',()=>edit('record'));
 document.querySelector<HTMLElement>('[data-edit-offer]')?.addEventListener('click',()=>edit('update'));
 document.querySelector<HTMLElement>('[data-upgrade-offer]')?.addEventListener('click',()=>edit('upgrade'));
 document.querySelector<HTMLElement>('[data-negotiation]')?.addEventListener('click',()=>{const d=dialog('记录谈薪沟通',`<form><p>沟通不会自动修改Offer条件；现实条件确认变化后请另行编辑当前Offer。</p><label>类型<select name="type"><option value="text">线上沟通</option><option value="phone">电话沟通</option><option value="other">其他沟通</option></select></label><label>日期<input type="date" name="occurred_on" value="${localDay()}" required></label><label>内容<textarea name="content" rows="7" required></textarea></label><button class="primary" type="submit">记录谈薪沟通</button></form>`);const f=d.querySelector<HTMLFormElement>('form')!;let key='';f.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f).entries());if(!key)key=crypto.randomUUID();try{await actions.api(`/opportunities/${encodeURIComponent(o.id)}/communications`,{...data,purpose:'negotiation',idempotency_key:key});d.close();await actions.refresh();actions.go(o.id);}catch(error){fail(d,error);}};});
 document.querySelector<HTMLElement>('[data-accept-offer]')?.addEventListener('click',()=>{const d=dialog('接受 Offer',`<p>这只会结束本次求职机会，不会创建任职记录。</p><form><button class="primary" type="submit">确认接受 Offer</button></form>`);const key=crypto.randomUUID();d.querySelector('form')!.addEventListener('submit',e=>{e.preventDefault();void(async()=>{try{await actions.api(`/opportunities/${encodeURIComponent(o.id)}/offer/${encodeURIComponent(offer!.id)}/accept`,{expected_opportunity_revision:o.revision,expected_offer_revision:offer!.revision,idempotency_key:key});d.close();await actions.refresh();actions.go(o.id,'ended');}catch(error){fail(d,error);}})();});});
}
